apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: healthchecks
  namespace: healthchecks
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`hc.lan.ftzmlab.xyz`)
    services:
    - name: healthchecks
      port: 8000
  tls: {}
