apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: healthchecks
    namespace: healthchecks
spec:
    secretTemplates:
        - name: healthchecks
          stringData:
            SECRET_KEY: ENC[AES256_GCM,data:Uq9wqK9nXaWI6b5gSL4Vf31sjLiTLRxHMR8aPAdIYejWkFDoPx1sDl1D03rawkGA2awgiNizYu0dpiPKdiOzfQ==,iv:3ALJawNHjkshwDO33D1a49T5xX3zKqlLeemoYCTRsF8=,tag:Wa8crhs1ZDsP56JNMLzxhg==,type:str]
            EMAIL_HOST_USER: ENC[AES256_GCM,data:e/Iaukiko7uxMEbLxQSzByE=,iv:6ZDhGpa4ktjuCkm+7NNAEuLIGFAXoHgNNoqLcDOyI5s=,tag:owDPpBuZ0DIk8si/j0pOLw==,type:str]
            EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:BBK5VSfG7otRGNGkbTWKtg==,iv:S/f8maVde4PrGt40jIlefsAysvPNsnKfwx1PITyy6Jo=,tag:aFNkeG0yBHUaHV/kBvB5lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ2xjaCtCS3hHZmZ5WXdu
            UE5adHhJc2k5OEQ1dWRwczAxcmUxc0RXajN3CjIyU3BEbmpSM25XajlBZ0RDdndt
            c3BlUFlFaEFwNzg0Zk1weTlnV1NzVm8KLS0tIDlqZ0pXaUNONzIxN3hWU0NFL2Rh
            L0REZHVVcFlRVTVaQlZtTm9TR3FGRVEKjo8sDwefzbrWvyh1SsE0iIutu84yNqkT
            9MsOKiv9qyuYaFnF+S4UPVJuRiHvYgQwfPLWvIU8kxT6eVl2VeP69w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3vw5n45s7cn3jy9g2duh969a9e22nvnt53m3wxpmmlnna3sls7szvwk7c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T13:05:22Z"
    mac: ENC[AES256_GCM,data:KJX+SgQTAEXYJ+LtEoODuzCzqu4/Zw6pxTaCUWHHNovcKiwO1aMbstSvhkD2YDRHGIeGxRSyIv/ukNK2aCjV64I7ZCYjVkL5gT0qNkAgHM+ZMOW/dPuRF7AwsPGH0yhmoQMft5ZWDkpXhYb8zS993rXcpofw6IJbTOQPp19lMLE=,iv:oily1ZzSspcSwUjdy6Iuxo5HOmQvcMKl4SBy4+yNNmQ=,tag:+tLaSMZnp8xUSGgpnKZpAQ==,type:str]
    version: 3.13.3
