apiVersion: v1
data:
  SIDECAR_IMAGE: ghcr.io/cloudnative-pg/plugin-barman-cloud-sidecar:v0.15.1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
  name: plugin-barman-cloud-config
  namespace: cnpg-system
