apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cleanuparr-config
    namespace: media
spec:
    secretTemplates:
        - name: cleanuparr-config
          stringData:
            CLEANUPARR_PASSWORD: ENC[AES256_GCM,data:0KbI94kn6J/BPfzfSx0yNRXdzzngpMAvD4R48FJ+IZQ=,iv:uWFG0jx/LZOioZSPlhOE773TmESGWehHSzqZKrpD5jU=,tag:2DlEXCFBFGeyb7LBdDygFg==,type:str]
            SONARR_API_KEY: ENC[AES256_GCM,data:Qh8uFzZt63jDIoOQdLZveRvH8R2xlJ4V46dT2jZAB14=,iv:HOTUqPZz6EyDEIx1VnOoq5haeQ5jgcA+1RRHmUIMkY4=,tag:CU/d8rJcAFH73vvw5eL30g==,type:str]
            RADARR_API_KEY: ENC[AES256_GCM,data:gZO5u8XlQ2IZ9QrMnjlXEcoLAfiKSDKzGm9XlfE9LBk=,iv:nemkMVf5PZABPebx0H6r7sSt4SHhhswauxS5AiVtGcY=,tag:aYViYnHi575kgLvwdJ+vTQ==,type:str]
            DELUGE_PASSWORD: ENC[AES256_GCM,data:CR+ScTQux94RHNlQlpU/8fwAveZwsmoP7A==,iv:1Id+tVmwXTQ/Re4dRsxN7cXQjTGGsBxbapv5WHgGKss=,tag:CurMtEAMj58wXtSBf0ameA==,type:str]
sops:
    age:
        - recipient: age1v3vw5n45s7cn3jy9g2duh969a9e22nvnt53m3wxpmmlnna3sls7szvwk7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZG9WbEYrcC8ydmh4Njlo
            RGJvMW5jaWNjYjNIYndLMXlCS0ZKWFhONjJvCjhFV1dhalBINzVKazVLdjQ0eW5Q
            ZFJKTmtCUlVuYmwrM3FBMUp0RHI0dVUKLS0tIGYxUnRNM21oQUhuVGNyR0IrRmxZ
            cURXU2thQWlQbWMvYkptVjhNVGdRTWcKxvz5CQwZ31lzjZGW0F9SD86FMHGW5Rd2
            WiUxjwh6t3wmaLZNHXUM0T881mhtPaU7f7Z+kiSp3HjVGOgcrnjLzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T08:38:33Z"
    mac: ENC[AES256_GCM,data:YI8PktlOp6cxul1/AUOl2tca6byMg+jsy0cRevJM1zQE9po9uKQ25WON4MQ5zt8T+lk09LBU8LuuDAd8A9Kw75BKz/y1VHyfcipxr9SazPCrYzRFyB9P6Ruqk7FYP85YpINQ+lsrEhSpU1KQEXw009NYYnyX/UrVvp1hhOJWf/w=,iv:o3Wdote2EXbDuXn36KYhYPm32cByu//hqCx/ZXMDMhU=,tag:fpcrdARc/OHXs6laWwS+LQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
