apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: forgejo-runner-monitor
  name: forgejo-runner-monitor
  namespace: forgejo
spec:
  ports:
  - name: http
    port: 7979
    targetPort: http
  selector:
    app.kubernetes.io/name: forgejo-runner-monitor
