apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-vaultwarden
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /pool-1/vaultwarden
    server: 192.168.1.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vaultwarden-vaultwarden
