import os

# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# ------------------------------------------------------------
# Setup
# ------------------------------------------------------------

# To silence errors while editing
# pylint: disable=C0111
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

# ------------------------------------------------------------
# Colors
# ------------------------------------------------------------

#color definitions
bg = "#282828"
light_bg = "#3c3836"
fg = "#ebdbb2"
dark_fg = "#7C6F64"

# statusbar
c.colors.statusbar.normal.bg = bg
c.colors.statusbar.normal.fg = dark_fg
c.colors.statusbar.url.fg = dark_fg
c.colors.statusbar.url.success.http.fg = dark_fg
c.colors.statusbar.url.success.https.fg = dark_fg
c.colors.statusbar.url.hover.fg = fg
c.colors.statusbar.command.bg = bg
c.colors.statusbar.command.fg = fg
c.colors.statusbar.progress.bg = fg

# Tab bar
c.colors.tabs.bar.bg = bg
c.colors.tabs.even.bg = bg
c.colors.tabs.even.fg = dark_fg
c.colors.tabs.odd.bg = bg
c.colors.tabs.odd.fg = dark_fg
c.colors.tabs.selected.even.bg = bg
c.colors.tabs.selected.even.fg = fg
c.colors.tabs.selected.odd.bg = bg
c.colors.tabs.selected.odd.fg = fg

# Completion
c.colors.completion.odd.bg = bg
c.colors.completion.even.bg = bg
c.colors.completion.fg = fg
c.colors.completion.category.border.top = light_bg
c.colors.completion.category.bg = light_bg
c.colors.completion.category.fg = fg
c.colors.completion.category.border.bottom = light_bg
c.colors.completion.scrollbar.bg = light_bg
c.colors.completion.scrollbar.fg = fg

# ------------------------------------------------------------
# Fonts
# ------------------------------------------------------------

c.fonts.default_family = [f"Iosevka Lig Medium"]
c.fonts.default_size = "8pt"

# ------------------------------------------------------------
# GUI
# ------------------------------------------------------------

c.tabs.position = "bottom"
c.tabs.show = "never"
c.tabs.favicons.show = "never"
c.tabs.indicator.width = 0
c.tabs.title.format = "{current_title}"

c.url.start_pages = ["file://" + os.path.expanduser("~/dev/homepage/index.html")]
c.url.searchengines = {"DEFAULT": "https://www.google.com/search?hl=en&q={}", "wa": "https://wiki.archlinux.org/?search={}"}

# ------------------------------------------------------------
# Bindings
# ------------------------------------------------------------

config.bind('b', 'set-cmd-text -s :buffer ')
