import os

# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# ------------------------------------------------------------
# Setup
# ------------------------------------------------------------

# To silence errors while editing
# pylint: disable=C0111
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

# ------------------------------------------------------------
# Colors
# ------------------------------------------------------------

#color definitions
bg = "#282828"
light_bg = "#3c3836"
fg = "#ebdbb2"
dark_fg = "#7C6F64"

# statusbar
c.colors.statusbar.normal.bg = bg
c.colors.statusbar.normal.fg = dark_fg
c.colors.statusbar.url.fg = dark_fg
c.colors.statusbar.url.success.http.fg = dark_fg
c.colors.statusbar.url.success.https.fg = dark_fg
c.colors.statusbar.url.hover.fg = fg
c.colors.statusbar.command.bg = bg
c.colors.statusbar.command.fg = fg
c.colors.statusbar.progress.bg = fg

# Tab bar
c.colors.tabs.bar.bg = bg
c.colors.tabs.even.bg = bg
c.colors.tabs.even.fg = dark_fg
c.colors.tabs.odd.bg = bg
c.colors.tabs.odd.fg = dark_fg
c.colors.tabs.selected.even.bg = bg
c.colors.tabs.selected.even.fg = fg
c.colors.tabs.selected.odd.bg = bg
c.colors.tabs.selected.odd.fg = fg

# Completion
c.colors.completion.odd.bg = bg
c.colors.completion.even.bg = bg
c.colors.completion.fg = fg
c.colors.completion.category.border.top = light_bg
c.colors.completion.category.bg = light_bg
c.colors.completion.category.fg = fg
c.colors.completion.category.border.bottom = light_bg
c.colors.completion.scrollbar.bg = light_bg
c.colors.completion.scrollbar.fg = fg

# ------------------------------------------------------------
# Fonts
# ------------------------------------------------------------

main_font = f"500 {os.getenv('FONT_SIZE', 16)}pt Fira Mono"
c.fonts.statusbar = main_font
c.fonts.completion.category = main_font
c.fonts.completion.entry = main_font
c.fonts.debug_console = main_font
c.fonts.downloads = main_font
c.fonts.hints = main_font
c.fonts.keyhint = main_font
c.fonts.messages.error = main_font
c.fonts.messages.info = main_font
c.fonts.messages.warning = main_font
c.fonts.monospace = main_font
c.fonts.prompts = main_font
c.fonts.statusbar = main_font
c.fonts.tabs = main_font

# ------------------------------------------------------------
# GUI
# ------------------------------------------------------------

c.tabs.position = "bottom"
c.tabs.show = "never"
c.tabs.favicons.show = "never"
c.tabs.indicator.width = 0
c.tabs.title.format = "{title}"

c.zoom.default = "100%"
c.url.start_pages = ["file:///home/matt/dev/homepage/index.html"]
c.url.searchengines = {"DEFAULT": "https://www.google.com/search?hl=en&q={}", "wa": "https://wiki.archlinux.org/?search={}"}

# ------------------------------------------------------------
# Bindings
# ------------------------------------------------------------

config.bind('b', 'set-cmd-text -s :buffer ')
