apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: pinepods-db-backup
  namespace: pinepods
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: pinepods-db-backup-pinepods
  volumeName: pinepods-db-backup-pinepods
