apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinepods-downloads
  namespace: pinepods
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: pinepods-downloads-pinepods
  volumeName: pinepods-downloads-pinepods
