apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pinepods-database-backup
  namespace: pinepods
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://cnpg-backups/pinepods
    endpointURL: http://192.168.1.3:3900
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: garage-cnpg
      region:
        key: REGION
        name: garage-cnpg
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: garage-cnpg
    wal:
      compression: gzip
  retentionPolicy: 30d
