apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: pinepods-db-backup-pinepods
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /pool-1/k8s/pinepods-db-backup
    server: 192.168.1.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pinepods-db-backup-pinepods
