apiVersion: v1
data:
  DB_HOST: pinepods-database-rw
  DB_NAME: pinepods_database
  DB_PORT: "5432"
  DB_TYPE: postgresql
  DB_USER: postgres
  DEBUG_MODE: "false"
  DEFAULT_LANGUAGE: en
  EMAIL: m@ftzm.org
  FULLNAME: ftzm
  HOSTNAME: https://pinepods.lan.ftzmlab.xyz
  PEOPLE_API_URL: https://people.pinepods.online
  PGID: "1001"
  PUID: "0"
  SEARCH_API_URL: https://search.pinepods.online/api/search
  TZ: Europe/Copenhagen
  USERNAME: ftzm
  VALKEY_HOST: valkey
  VALKEY_PORT: "6379"
kind: ConfigMap
metadata:
  name: pinepods-env
  namespace: pinepods
