apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastack
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: mediastack-media
  volumeName: mediastack-media
