apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediastack-media
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /pool-1/mediastack
    server: 192.168.1.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mediastack-media
