apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
spec:
    secretTemplates:
        - name: cloudflare-api-token
          stringData:
            api-token: ENC[AES256_GCM,data:Nj/Fu/GiHg9gvZhgTdrGPzVF8GfrUdtPyTn8uON1O5r7pmz6IDAepg==,iv:YU14oNLpAxoFHfSLG0fDGgqBc20UM2LHN8FUCvJyLN8=,tag:wjvzf3Reupl/ATTDIc/paQ==,type:str]
sops:
    age:
        - recipient: age1v3vw5n45s7cn3jy9g2duh969a9e22nvnt53m3wxpmmlnna3sls7szvwk7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajFuOWc5ZUw0RnFNYU4y
            WlpuTFp4bjNTYmZaNld0TWczMWUvelFXbURRCnlsRmhsYUdEbWl6T2xpT2ZrNit5
            UUZHSDA0UWFhcmVQeHEzVXV1M1hveEUKLS0tIHFtMVVobXVtd3k4WjVhZ20xaUlP
            UWtNTDlCcjRTVlhMUUxocUVRZ3R0bTAKVqlysF1LEaQUzJKTN93tyq0YaqroX11x
            6Z/7rf66TQcPJeQRhx/Z19LAQM7Nn5erlFpjUpSbs6OcfM1B0QzH7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T10:12:56Z"
    mac: ENC[AES256_GCM,data:Q4rXzkCnH6J+YKNmB5LvNyFl2NhnosTaxyPoSs1FhCPjYgiaYzd6X1WfqXoR64tUh3NiDt0Q4lqU8hSMXg3EhfWsGS8EOe9Jki2FSstAjkG0h8A5G20Ojlsvx2Kv1YXb6lWKMJr0i1vj4ADoqBU8WFrBmjkSmMqrYoQH7j4oTXk=,iv:jAdlXBRVvzIqc5w7YOHu3qlCYSdNCp7T2gyAgAlAEr4=,tag:MH6DbxYqx5Lw+fFynU56OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
