apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/version: 0.40.0
    helm.sh/chart: sealed-secrets-2.20.0
  name: sealed-secrets
  namespace: sealed-secrets
