apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: audiobooks-audiobookshelf
  volumeName: audiobooks-audiobookshelf
