apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cleanuparr
  namespace: media
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`cleanuparr.lan.ftzmlab.xyz`)
    services:
    - name: cleanuparr
      port: 11011
  tls: {}
