apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.23.0
    helm.sh/chart: external-dns-1.23.0
  name: external-dns
  namespace: external-dns
