apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filestash
  namespace: default
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`filestash.lan.ftzmlab.xyz`)
    services:
    - name: filestash
      port: 8334
  tls: {}
