apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: filestash
  name: filestash
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8334
    protocol: TCP
    targetPort: 8334
