apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-backup
  namespace: forgejo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: forgejo-backup-forgejo
  volumeName: forgejo-backup-forgejo
