apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo
  namespace: forgejo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: forgejo-forgejo
  volumeName: forgejo-forgejo
