apiVersion: v1
data:
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Cluster Overview:
      - "":
          widget:
            classes: h-48 w-full
            name: grafana-overview
            referrerPolicy: same-origin
            src: https://grafana.lan.ftzmlab.xyz/d/homepage-overview/homepage-overview?orgId=1&theme=dark&kiosk
            type: iframe
    - Media:
      - Radarr:
          href: https://radarr.lan.ftzmlab.xyz
          icon: radarr
          ping: https://radarr.lan.ftzmlab.xyz
          widget:
            key: '{{HOMEPAGE_VAR_RADARR_KEY}}'
            type: radarr
            url: http://radarr.media.svc.cluster.local:7878
      - Sonarr:
          href: https://sonarr.lan.ftzmlab.xyz
          icon: sonarr
          ping: https://sonarr.lan.ftzmlab.xyz
          widget:
            key: '{{HOMEPAGE_VAR_SONARR_KEY}}'
            type: sonarr
            url: http://sonarr.media.svc.cluster.local:8989
      - Lidarr:
          href: https://lidarr.lan.ftzmlab.xyz
          icon: lidarr
          ping: https://lidarr.lan.ftzmlab.xyz
          widget:
            key: '{{HOMEPAGE_VAR_LIDARR_KEY}}'
            type: lidarr
            url: http://lidarr.media.svc.cluster.local:8686
      - Readarr:
          href: https://readarr.lan.ftzmlab.xyz
          icon: readarr
          ping: https://readarr.lan.ftzmlab.xyz
          widget:
            key: '{{HOMEPAGE_VAR_READARR_KEY}}'
            type: readarr
            url: http://readarr.media.svc.cluster.local:8787
      - Prowlarr:
          href: https://prowlarr.lan.ftzmlab.xyz
          icon: prowlarr
          ping: https://prowlarr.lan.ftzmlab.xyz
          widget:
            key: '{{HOMEPAGE_VAR_PROWLARR_KEY}}'
            type: prowlarr
            url: http://prowlarr.media.svc.cluster.local:9696
      - Jellyseerr:
          href: https://jellyseerr.lan.ftzmlab.xyz
          icon: jellyseerr
          ping: https://jellyseerr.lan.ftzmlab.xyz
      - Jellyfin:
          href: https://jellyfin.ftzmlab.xyz
          icon: jellyfin
    - Apps:
      - Immich:
          href: https://img.lan.ftzmlab.xyz
          icon: immich
          ping: https://img.lan.ftzmlab.xyz
          widget:
            key: '{{HOMEPAGE_VAR_IMMICH_KEY}}'
            type: immich
            url: http://immich-server.immich.svc.cluster.local:2283
            version: 2
      - Navidrome:
          href: https://navidrome.lan.ftzmlab.xyz
          icon: navidrome
          ping: https://navidrome.lan.ftzmlab.xyz
      - Audiobookshelf:
          href: https://audiobookshelf.lan.ftzmlab.xyz
          icon: audiobookshelf
          ping: https://audiobookshelf.lan.ftzmlab.xyz
      - Vaultwarden:
          href: https://vaultwarden.lan.ftzmlab.xyz
          icon: vaultwarden
          ping: https://vaultwarden.lan.ftzmlab.xyz
      - The Lounge:
          href: https://irc.lan.ftzmlab.xyz
          icon: thelounge
          ping: https://irc.lan.ftzmlab.xyz
      - ntfy:
          href: https://ntfy.lan.ftzmlab.xyz
          icon: ntfy
          ping: https://ntfy.lan.ftzmlab.xyz
    - Infrastructure:
      - ArgoCD:
          href: https://argo.lan.ftzmlab.xyz
          icon: argocd
      - Grafana:
          href: https://grafana.lan.ftzmlab.xyz
          icon: grafana
      - Traefik:
          icon: traefik
  settings.yaml: |
    title: ftzmlab
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Cluster Overview:
        style: row
        columns: 1
      Media:
        style: row
        columns: 4
      Apps:
        style: row
        columns: 3
      Infrastructure:
        style: row
        columns: 3
  widgets.yaml: |
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: homepage-2.1.0
  name: homepage
  namespace: homepage
