apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: homepage
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: homepage-2.1.0
  name: homepage-sa-token
  namespace: homepage
type: kubernetes.io/service-account-token
