apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: immich
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: immich-photos-immich
  volumeName: immich-photos-immich
