apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
      - CREATE EXTENSION vchord CASCADE;
      - CREATE EXTENSION earthdistance CASCADE;
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  instances: 1
  postgresql:
    shared_preload_libraries:
    - vchord.so
  storage:
    size: 5Gi
    storageClass: nfs
