apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-backup
  namespace: immich
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: immich-db-backup-immich
  volumeName: immich-db-backup-immich
