addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.168.1.4
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: immich
  name: immich
  namespace: default
ports:
- name: http
  port: 2343
  protocol: TCP
