apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: immich
  name: immich
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 2343
    protocol: TCP
    targetPort: 2343
