apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-backup-immich
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /pool-1/k8s/immich-db-backup
    server: 192.168.1.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-db-backup-immich
