apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
      - CREATE EXTENSION vchord CASCADE;
      - CREATE EXTENSION earthdistance CASCADE;
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 16
    name: vectorchord
  instances: 1
  postgresql:
    shared_preload_libraries:
    - vchord.so
  storage:
    size: 5Gi
    storageClass: nfs
