apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: media
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`jellyseerr.lan.ftzmlab.xyz`)
    services:
    - name: jellyseerr
      port: 5055
  tls: {}
