apiVersion: v1
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogaG9zdC1ub2RlLWV4cG9ydGVyCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSBsYWJlbHM6CiAgICAgIGluc3RhbmNlOiBudWMKICAgICAgam9iOiBub2RlLWV4cG9ydGVyCiAgICB0YXJnZXRzOgogICAgLSAxOTIuMTY4LjEuNDo5MDAyCiAgLSBsYWJlbHM6CiAgICAgIGluc3RhbmNlOiBuYXMKICAgICAgam9iOiBub2RlLWV4cG9ydGVyCiAgICB0YXJnZXRzOgogICAgLSAxOTIuMTY4LjEuMzo5MDAyCiAgLSBsYWJlbHM6CiAgICAgIGluc3RhbmNlOiBzYW9pc3RlCiAgICAgIGpvYjogbm9kZS1leHBvcnRlcgogICAgdGFyZ2V0czoKICAgIC0gMTAwLjY0LjAuMTo5MDAyCiAgLSBsYWJlbHM6CiAgICAgIGluc3RhbmNlOiBlYWNodHJhaQogICAgICBqb2I6IG5vZGUtZXhwb3J0ZXIKICAgIHRhcmdldHM6CiAgICAtIDEwMC42NC4wLjc6OTAwMgotIGpvYl9uYW1lOiBjb21pbgogIHN0YXRpY19jb25maWdzOgogIC0gbGFiZWxzOgogICAgICBpbnN0YW5jZTogbnVjCiAgICB0YXJnZXRzOgogICAgLSAxOTIuMTY4LjEuNDo0MjQzCiAgLSBsYWJlbHM6CiAgICAgIGluc3RhbmNlOiBuYXMKICAgIHRhcmdldHM6CiAgICAtIDE5Mi4xNjguMS4zOjQyNDMKICAtIGxhYmVsczoKICAgICAgaW5zdGFuY2U6IHNhb2lzdGUKICAgIHRhcmdldHM6CiAgICAtIDEwMC42NC4wLjE6NDI0MwogIC0gbGFiZWxzOgogICAgICBpbnN0YW5jZTogZWFjaHRyYWkKICAgIHRhcmdldHM6CiAgICAtIDEwMC42NC4wLjc6NDI0Mw==
kind: Secret
metadata:
  labels:
    app: kube-prometheus-stack-prometheus-scrape-confg
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 90.1.1
    chart: kube-prometheus-stack-90.1.1
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-prometheus-scrape-confg
  namespace: monitoring
