apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: navidrome
  name: navidrome
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 4533
    protocol: TCP
    targetPort: 4533
