apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: navidrome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: navidrome
    spec:
      containers:
      - env:
        - name: ND_MUSICFOLDER
          value: /music
        image: ghcr.io/navidrome/navidrome:0.61.2
        name: navidrome
        ports:
        - containerPort: 4533
          name: http
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /music
          name: music
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: navidrome-config
      - name: music
        persistentVolumeClaim:
          claimName: music
