apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ntfy
    spec:
      containers:
      - args:
        - serve
        image: binwiederhier/ntfy
        name: ntfy
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /etc/ntfy
          name: config
        - mountPath: /var/cache/ntfy
          name: cache
      volumes:
      - configMap:
          name: ntfy-config
        name: config
      - name: cache
        persistentVolumeClaim:
          claimName: ntfy-cache
