apiVersion: batch/v1
kind: CronJob
metadata:
  name: pinepods-db-backup
  namespace: pinepods
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - pg_dump --format=custom --file=/backup/pinepods-db-backup-$(date +%Y%m%d-%H%M%S).dump
              && find /backup -name "*.dump" -mtime +7 -delete
            command:
            - /bin/sh
            - -c
            env:
            - name: PGHOST
              value: pinepods-database-rw
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: pinepods_database
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pinepods-database-superuser
            image: ghcr.io/cloudnative-pg/postgresql:18.4
            name: pg-dump
            volumeMounts:
            - mountPath: /backup
              name: backup
          restartPolicy: OnFailure
          securityContext:
            supplementalGroups:
            - 1001
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: pinepods-db-backup
  schedule: 0 3 * * *
  successfulJobsHistoryLimit: 3
