apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pinepods-database
  namespace: pinepods
spec:
  bootstrap:
    initdb:
      database: pinepods_database
      owner: pinepods
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:18.2
  instances: 1
  storage:
    size: 5Gi
    storageClass: nfs
