apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pinepods
  namespace: pinepods
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`pinepods.lan.ftzmlab.xyz`)
    services:
    - name: pinepods
      port: 8040
  tls: {}
