apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.10.1
    helm.sh/chart: tempo-2.1.0
  name: tempo
  namespace: monitoring
