apiVersion: v1
data:
  config.yml: |-
    "http":
      "routers":
        "audiobookshelf":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`audiobookshelf.lan.ftzmlab.xyz`)"
          "service": "audiobookshelf"
        "deluge":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`deluge.lan.ftzmlab.xyz`)"
          "service": "deluge"
        "filestash":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`filestash.lan.ftzmlab.xyz`)"
          "service": "filestash"
        "immich":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`img.lan.ftzmlab.xyz`)"
          "service": "immich"
        "jellyfin":
          "entryPoints":
          - "web"
          - "websecure"
          "rule": "Host(`jellyfin.ftzmlab.xyz`)"
          "service": "jellyfin"
        "navidrome":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`navidrome.lan.ftzmlab.xyz`)"
          "service": "navidrome"
        "vaultwarden":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`vaultwarden.lan.ftzmlab.xyz`)"
          "service": "vaultwarden"
        "webdav":
          "entryPoints":
          - "privateweb"
          - "privatesecure"
          - "wgweb"
          - "wgsecure"
          "rule": "Host(`dav.lan.ftzmlab.xyz`)"
          "service": "webdav"
      "services":
        "audiobookshelf":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:8000"
        "deluge":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:8112"
        "filestash":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:8334"
        "immich":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:2283"
        "jellyfin":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:8096"
        "navidrome":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:4533"
        "vaultwarden":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:8222"
        "webdav":
          "loadBalancer":
            "servers":
            - "url": "http://127.0.0.1:8085"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-39.0.0
  name: traefik-file-provider
  namespace: traefik
