apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: pinepods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - image: valkey/valkey:8-alpine
        name: valkey
        ports:
        - containerPort: 6379
