apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: default
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`vaultwarden.lan.ftzmlab.xyz`)
    services:
    - name: vaultwarden
      port: 8222
  tls: {}
