apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: vaultwarden-vaultwarden
  volumeName: vaultwarden-vaultwarden
