apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vaultwarden
  name: vaultwarden
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8222
    protocol: TCP
    targetPort: 8222
