apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
