apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: vaultwarden-env
    namespace: vaultwarden
spec:
    secretTemplates:
        - name: vaultwarden-env
          stringData:
            ADMIN_TOKEN: ENC[AES256_GCM,data:mI65OpaTjw5FhkQyjtDqqMBK,iv:/muoMgJxXCGh8yK213+83kplnuLKy8Dhp/703Kydmxo=,tag:wtGXfJjIWoXZSJ1FmmoBgw==,type:str]
sops:
    age:
        - recipient: age1v3vw5n45s7cn3jy9g2duh969a9e22nvnt53m3wxpmmlnna3sls7szvwk7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbWIwLzRtY28wNVJqQU1H
            cFZ5dUhWcDRVUjRPa2NOU0NzUU9Cdkg1MzJvClJxc3M2T1hwZk1SdXZ0OVYrM3ov
            OStHM09ZOWowSkN1bVRmM2JraGJLb0EKLS0tIHd6eHl6angxTlN2OUhPSjZSZWdw
            NklOYlVoTWRNUFo5MmtIWkRueDRQZk0KtI9wGDXumdRoy2g1w98QXB5pmwm5upPd
            5tO/wc1AthiUOio/VKO9PwwdMNRRD93Fw6HPIM5PA8m49GIm1jnMlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T20:35:57Z"
    mac: ENC[AES256_GCM,data:/L+f86XzuwmYAx/FODuJP8OtbC6TeqIcv26soBudOm/jAPTKQZpgJIJgKlTgLTK0PmKUHoW3gu4uiC/3KjS/Ld5YiGIuPvCAmS1QOjQvApZBTSKDgbMjbmct84q4bzrdCT8KCvwnFESQHQwml95f+/bVw4rEM5wQKQsJAR3tQQU=,iv:lQOnNJ4wQMt3IeHfmte+F8CcOCiOgA5OcDWs4Le+NCA=,tag:QhvHu4XjvsbpaefvYqW2gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
