apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: vectorchord
  namespace: default
spec:
  images:
  - image: ghcr.io/tensorchord/cloudnative-vectorchord:16.14-1.1.1
    major: 16
