apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webdav
  namespace: default
spec:
  entryPoints:
  - privateweb
  - privatesecure
  - wgweb
  - wgsecure
  routes:
  - kind: Rule
    match: Host(`dav.lan.ftzmlab.xyz`)
    services:
    - name: webdav
      port: 8080
  tls: {}
