apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: miniflux
  namespace: miniflux
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app: miniflux
