apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-database
  namespace: miniflux
spec:
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 18
    name: postgresql
  instances: 1
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: miniflux-database-backup
      serverName: miniflux-database-g1
  storage:
    size: 5Gi
    storageClass: nfs
