apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
    prometheus.io/service-monitor: "false"
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- include "tempo.udp" . | indent 2 }}
    {{- include "tempo.tcp" . | indent 2 }}
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
