apiVersion: v2
appVersion: 0.20.1
description: Helm chart deploys sops-secrets-operator
keywords:
- gitops
- sops
- kms
- encryption
- secret
- git
maintainers:
- email: isindir@users.sf.net
  name: isindir
name: sops-secrets-operator
sources:
- https://github.com/isindir/sops-secrets-operator.git
type: application
version: 0.25.3
