apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: nfs-provisioner
  namespace: argocd
spec:
  destination:
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/manifests/nfs-provisioner
    repoURL: https://github.com/ftzm/dots.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
